### ISSUE TITLE
Unable to load crimson_forest

### ISSUE THREAD

**Issue by BigAppleClass** [BentoBoxWorld/Biomes#141]
### Expected behavior

/bsb biomes Import the template /is biomes display

### Observed/Actual behavior

Not shown

### Steps/models to reproduce
```
# 绯红森林
  crimson_forest:
    biome: crimson_forest
    environment: normal
    name: '&b绯红森林'
    icon: crimson_nylium
  crimson_forest:
    biome: crimson_forest
    environment: nether
    name: '&b绯红森林'
    icon: crimson_nylium
  crimson_forest:
    biome: crimson_forest
    environment: the_end
    name: '&b绯红森林'
    icon: crimson_nylium 
```
### BentoBox version

![image](https://github.com/user-attachments/assets/978cdc4a-6bb2-4a88-b962-3fad21710184)

### Plugin list

![image](https://github.com/user-attachments/assets/5361bfd8-2f43-46e2-a1e3-ca61b22090ab)

**Comment by tastybento** [comment]
Biomes can only have one environment, so this should work:

```
# 绯红森林
  crimson_forest:
    biome: crimson_forest
    environment: normal
    name: '&b绯红森林'
    icon: crimson_nylium
```

If you need them in different environments then call them something different. YAML does not allow the same tag to be used multiple times.
