### ISSUE TITLE
Biomes default-mode ignored

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Biomes#98]
### Expected behavior

Respect the default mode
Clear text to inform player to implications

### Observed/Actual behavior

Left clicking in the main `/is biomes` panel immediately changes the whole island into that biome.
There is no warning what the implications are for the players. `Click to apply` is way to common and even misleading.
![Biomes-selection1](https://user-images.githubusercontent.com/28690790/156565279-7e2351d0-ae36-4b4e-862f-e17d33e24b3e.png)
![Biomes-selection3](https://user-images.githubusercontent.com/28690790/156565412-5354fa8c-4570-4e8f-b88b-fa67a01a01a5.png)
I could edit the language files to be more clear to players. But that doesn't solve the main problem that this panel does not respect the default mode.

### Steps/models to reproduce

- Test server with fresh, default bentobox, bskyblock and biomes.
- Change biomes comfig: `default-mode: CHUNK`
- restart
- Choose an island
- execute: `is biomes`
- right click on any biome to check that the default mode is set to chunk, marked with the glowing effect on the chunk icon.
- back
- in the main biome panel, left click on any biome
- see result that complete island is converted to choosen biome

### BentoBox version

Running PURPUR 1.18.1.
BentoBox version: 1.20.0
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, The End
Loaded Addons:
Biomes 2.0.0-SNAPSHOT-b220 (ENABLED)
BSkyBlock 1.15.2-SNAPSHOT-b718 (ENABLED)

### Plugin list

N/A

### Other

![Biomes-selection2](https://user-images.githubusercontent.com/28690790/156566526-a5ba387f-9a22-4e26-94c7-2e90cf13e882.png)

**Comment by BONNe** [comment]
If you use default GUI panels, then the "left-click" action is defined with `ISLAND` mode:

https://github.com/BentoBoxWorld/Biomes/blob/c3c9aa53117f05b282429cb5f04e5811f3772c22/src/main/resources/panels/main_panel.yml#L77-L80

As it is specified to be `ISLAND` mode in GUI panel config, then the default mode is ignored. 

Currently, the default mode and range are in a weird spot. It is used for starting values in the Advanced Panel and values for the biome change command if nothing has been specified.

**Comment by x1p** [comment]
I overlooked that setting. Weird spot. But ok, if it works, it works.

**Comment by BONNe** [comment]
Well, the reason is simple:

```
       left:
          type: CHANGE
          content: ISLAND
          tooltip: "Left click to change Biome on the whole Island"
        shift-left:
          type: CHANGE
          content: CHUNK:1
          tooltip: "Left-shift click to change Biome on single chunk"
        right:
          type: BUY
          tooltip: "Right click to buy Biome"
```          

Without the ability to specify what to run on click, it would not be possible to allow different change modes with different clicks. 
F.e. this is how I use it in my setup.
